CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "firstName" VARCHAR(100) NOT NULL,
  "lastName" VARCHAR(100) NOT NULL,
  phone VARCHAR(20) UNIQUE NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  status INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS userbio (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  userid INTEGER NOT NULL REFERENCES users(id),
  address VARCHAR(255),
  occupation VARCHAR(100),
  nextofkin VARCHAR(100),
  k_phone VARCHAR(20),
  k_relationship VARCHAR(100),
  k_address VARCHAR(255),
  kra_pin VARCHAR(50),
  identification_card VARCHAR(255),
  status INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bankdetails (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  userid INTEGER NOT NULL REFERENCES users(id),
  bank VARCHAR(100),
  account_number VARCHAR(50),
  account_name VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admins (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS accounts (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  userid INTEGER NOT NULL UNIQUE REFERENCES users(id),
  balance NUMERIC(12, 2) DEFAULT 0,
  last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS otp (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email VARCHAR(100) NOT NULL,
  code VARCHAR(10) NOT NULL,
  hash VARCHAR(255),
  datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS portfolio (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  product VARCHAR(100),
  product_name VARCHAR(100),
  description TEXT,
  qty NUMERIC(10, 2) DEFAULT 0,
  quantity NUMERIC(10, 2),
  cost NUMERIC(10, 2),
  buy_price NUMERIC(10, 2),
  sellingprice NUMERIC(10, 2),
  sell_price NUMERIC(10, 2),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "order" (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  userid INTEGER NOT NULL REFERENCES users(id),
  productid INTEGER REFERENCES portfolio(id),
  quantity NUMERIC(10, 2),
  price NUMERIC(10, 2),
  expiry TIMESTAMP,
  type INTEGER,
  status INTEGER DEFAULT 0,
  receipt_id INTEGER,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS receipts (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  orderid INTEGER REFERENCES "order"(id),
  product_name VARCHAR(100),
  qty NUMERIC(10, 2),
  price NUMERIC(10, 2),
  tx VARCHAR(255),
  status INTEGER DEFAULT 1,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS initiatedtransactions (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  userid INTEGER REFERENCES users(id),
  phone VARCHAR(20),
  amount NUMERIC(12, 2),
  receipt VARCHAR(100),
  status INTEGER DEFAULT 0,
  "CheckoutRequestID" VARCHAR(255),
  "startedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS withdraw (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  userid INTEGER NOT NULL REFERENCES users(id),
  amount NUMERIC(12, 2),
  phone VARCHAR(20),
  bank VARCHAR(100),
  acountnumber VARCHAR(50),
  acountname VARCHAR(100),
  type VARCHAR(20),
  lastupdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status INTEGER DEFAULT 0
);

INSERT INTO users ("firstName", "lastName", phone, email, password, status)
VALUES ('Test', 'User', '+254712345678', 'test@test.com', '$2b$10$K0L0aXPrWRdCY7E7vM3F5.2rW7s7Z1K8L9M0N1O2P3Q4R5S6T7U8V', 0)
ON CONFLICT (email) DO NOTHING;
